services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: krs_app
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDRESS=redis:6379
      - APP_PORT=50051
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservice_net

  redis:
    image: redis:7-alpine
    container_name: redis_storage
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - microservice_net

networks:
  microservice_net:
    driver: bridge